get exercises back
GSG-G9/calorie-tracker pull request #126
Opened 2021-02-17 09:04 UTC by zeinjendeya

- query to get all exercises from the database
- controller to get all exercises and send them to the front
- added it to the router file
- 
#39

2021-02-17 11:04 UTC, tomduggan85 commented
This all looks good to me! Adding a test might be a good next step.

2021-02-17 14:15 UTC, khamis-hesham submitted a review, later dismissed

2021-02-17 14:18 UTC, imansedky5 approved these changes

2021-02-17 21:47 UTC, hassanelnajjar requested changes

2021-02-17 21:47 UTC, hassanelnajjar commented on server/database/queries/getExercise.js
> +const getExercises = () => connection.query('SELECT * FROM exercises');
Zein, This query will not fit our front , you will not show the met value to the user, is important to show calories/hr for each exercise so you need here to get the user weight and multiply be the met value.
Also, we need to make a check on the user exercise, so also you need the userExersices Table also.
I think we need to make the following three queries and then handle it's in the controller and send them back to the front.

```sql
const userWeight = connection.query({
    text: 'SELECT weight from users where id=$1',
    values: [userId],
  });

  const exercises = connection.query('SELECT * FROM exercises');

  const userExercises = connection.query(
    'SELECT id,exercises_id ,exercise_duration_in_minutes as duration from UserExerciseRelation where users_id=$1 and created_at=current_date',
    [userId],
  );
```

2021-02-18 08:32 UTC, lina-jamal approved these changes

2021-02-18 08:33 UTC, khamis-hesham approved these changes

2021-02-18 08:34 UTC, hassanelnajjar approved these changes

2021-02-18 08:34 UTC, imansedky5 approved these changes

2021-02-18 08:34 UTC, merged