initial server created
GSG-G9/calorie-tracker pull request #54
Opened 2021-02-01 12:25 UTC by imansedky5

-  Install express package
-  Create app using express 
- Server listen to port 5000
- Added  Scripts to Package.json file (start,dev, kill)
- Added  Add Proxy to react folder package.josn

2021-02-01 12:38 UTC, hassanelnajjar commented on server/index.js
> +app.listen(port, () => console.log('hey from port 5000'));
In app.js file, you set the port but you didn't use it here

2021-02-01 13:00 UTC, hassanelnajjar commented on package.json
> +  "proxy": "http://localhost:4000"
please,change the port number, I set the port 5000 for server not 4000

2021-02-01 13:00 UTC, hassanelnajjar requested changes
branch name should begin with the issue number like 47-create-initial-server

2021-02-02 09:33 UTC, hassanelnajjar approved these changes

2021-02-02 09:34 UTC, hassanelnajjar approved these changes

2021-02-02 09:35 UTC, khamis-hesham approved these changes

2021-02-02 09:36 UTC, zeinjendeya submitted a review, later dismissed

2021-02-02 09:42 UTC, hassanelnajjar submitted a review, later dismissed

2021-02-02 10:09 UTC, zeinjendeya approved these changes

2021-02-02 10:14 UTC, lina-jamal commented on .gitignore
> +client/.eslintcache
add new line at the end

2021-02-02 10:14 UTC, lina-jamal commented on client/.eslintcache
> +[{"/home/iman/calorie-tracker/client/src/index.js":"1","/home/iman/calorie-tracker/client/src/App.js":"2"},{"size":168,"mtime":1612179889152,"results":"3","hashOfConfig":"4"},{"size":148,"mtime":1612
put this file in gitignore

2021-02-02 11:13 UTC, lina-jamal approved these changes

2021-02-02 11:22 UTC, hassanelnajjar approved these changes

2021-02-02 12:13 UTC, khamis-hesham approved these changes

2021-02-02 12:14 UTC, merged