added food fake data
GSG-G9/calorie-tracker pull request #74
Opened 2021-02-02 18:59 UTC by imansedky5

Added fake data in food_type, nutrition and food table

2021-02-02 19:05 UTC, zeinjendeya submitted a review, later dismissed

2021-02-03 07:39 UTC, khamis-hesham approved these changes

2021-02-03 09:04 UTC, hassanelnajjar requested changes
Food type is just meal and food,The table food_type is just a two record table. may be zero for food and 1 for meal.
The Food table need to add food_name and food_type and also image
```sql
INSERT INTO food(food_type, food_name,img) values (0, 'egg','imageUr');
```

2021-02-03 12:55 UTC, khamis-hesham approved these changes

2021-02-04 07:11 UTC, lina-jamal approved these changes

2021-02-04 07:25 UTC, hassanelnajjar approved these changes

2021-02-04 07:30 UTC, khamis-hesham submitted a review, later dismissed

2021-02-04 07:59 UTC, hassanelnajjar approved these changes

2021-02-04 08:00 UTC, zeinjendeya approved these changes

2021-02-04 08:00 UTC, lina-jamal approved these changes

2021-02-04 08:00 UTC, khamis-hesham approved these changes

2021-02-04 08:01 UTC, merged