49 loading progress bar component
GSG-G9/calorie-tracker pull request #81
Opened 2021-02-03 06:59 UTC by imansedky5

LoadingProgressBar Component done

2021-02-03 07:44 UTC, zeinjendeya approved these changes

2021-02-03 09:06 UTC, hassanelnajjar requested changes
Please separate the fake data - checkbox from this pull request.

2021-02-04 08:56 UTC, hassanelnajjar requested changes
Please pull the main - make a folder for the component and remove any not related files

2021-02-09 08:38 UTC, lina-jamal approved these changes

2021-02-09 08:39 UTC, zeinjendeya approved these changes

2021-02-09 08:39 UTC, hassanelnajjar approved these changes

2021-02-09 08:41 UTC, khamis-hesham approved these changes

2021-02-09 08:42 UTC, merged

2021-02-09 11:19 UTC, tomduggan85 commented on client/src/components/Loading/index.js
> +      <CircularProgress size={70} thickness={4} />
I think you will want this LoadingProgressBar component to take a `value` prop and then pass that `value` into the `CircularProgress` here.  But of course that can be a next step, when you are ready to use this component in the real app.