84 theme provider
GSG-G9/calorie-tracker pull request #93
Opened 2021-02-05 21:41 UTC by hassanelnajjar

#Create Theme Provider
- [ ] Create Theme Provider component using theme provider in material-UI
- [ ] Create A Test Component as a practical application of this theme
- [ ] Create our palette in the theme and add our colors into it
- [ ] Change the primary and secondary colors

#84

2021-02-07 14:43 UTC, lina-jamal requested changes

2021-02-07 14:43 UTC, lina-jamal commented on client/src/components/TestComponent/index.js
> +}
remove the test component from the pull request

2021-02-08 09:47 UTC, imansedky5 approved these changes

2021-02-08 09:50 UTC, zeinjendeya approved these changes

2021-02-08 10:15 UTC, lina-jamal approved these changes

2021-02-08 10:17 UTC, khamis-hesham approved these changes

2021-02-08 10:17 UTC, merged